<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>cdcpd</name>
  <version>0.1.0</version>
  <description>tracking for rope and cloth</description>
  <url type="repository">https://github.com/UM-ARM-Lab/cdcpd</url>
  <maintainer email="dmcconac@umich.edu">Dale McConachie</maintainer>
  <author email="chicheng@umich.edu">Cheng Chi</author>
  <author email="dmcconac@umich.edu">Dale McConachie</author>
  <author email="anveepnaik@gmail.com">Anvee Naik</author>
  <author email="spschul@umich.edu">Steven Schulte</author>
  <author email="yixuanwa@umich.edu">Yixuan Wang</author>
  <author email="pmitrano@umich.edu">Peter Mitrano</author>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>geometric_shapes</depend>
  <depend>jsk_recognition_msgs</depend>
  <depend>image_geometry</depend>
  <depend>image_transport</depend>
  <depend>moveit_ros_planning</depend>
  <depend>moveit_ros_planning_interface</depend>
  <depend>moveit_msgs</depend>
  <depend>moveit_visual_tools</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>sdf_tools</depend>
  <depend>smmap_models</depend>
  <depend>smmap_utilities</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

